### ISSUE TITLE
Performance Improvements SoCraTes Registration

### ISSUE THREAD

**Issue by rradczewski** [softwerkskammer/Agora#1073]
## Requirements
- [ ] Testbares Setup mit `node v5.7.1`
- [ ] Zuverlässige Performance Messung
## Todo
- [x] ReadModels und Events im State speichern, nur bei Cold-Start rehydrieren
- [ ] v8-profiler laufen lassen und flame-graphs machen (dafür brauchen wir Testdaten)
